Repository input-output-hk/partner-chains-smart-contracts, pull requests merged in 2024-08, with the labels that each got.

#47 693/onchain ghc9.x putus 1.27
  flake.lock
  flake.nix
  nix/onchain.nix
  offchain/src/TrustlessSidechain/RawScripts.purs
  offchain/test/Test/MerkleRootChaining.purs
  offchain/test/Test/PoCRawScripts.purs
  onchain/app/gen-signatures/GenOutput.hs
  onchain/app/gen-signatures/GetOpts.hs
  onchain/app/serialise/Main.hs
  onchain/cabal.project
  onchain/poc/TrustlessSidechain/PoCAlwaysPassingScripts.hs
  onchain/poc/TrustlessSidechain/PoCECDSA.hs
  onchain/poc/TrustlessSidechain/PoCInlineDatum.hs
  onchain/poc/TrustlessSidechain/PoCMintingPolicy.hs
  onchain/poc/TrustlessSidechain/PoCReferenceInput.hs
  onchain/poc/TrustlessSidechain/PoCReferenceScript.hs
  onchain/poc/TrustlessSidechain/PoCSchnorr.hs
  onchain/poc/TrustlessSidechain/PoCSerialiseData.hs
  onchain/prelude/TrustlessSidechain/PlutusPrelude/TH.hs
  onchain/src/TrustlessSidechain/CandidatePermissionMintingPolicy.hs
  onchain/src/TrustlessSidechain/CheckpointValidator.hs
  onchain/src/TrustlessSidechain/CommitteeCandidateValidator.hs
  onchain/src/TrustlessSidechain/CommitteePlainATMSPolicy.hs
  onchain/src/TrustlessSidechain/CommitteePlainEcdsaSecp256k1ATMSPolicy.hs
  onchain/src/TrustlessSidechain/CommitteePlainSchnorrSecp256k1ATMSPolicy.hs
  onchain/src/TrustlessSidechain/DParameter.hs
  onchain/src/TrustlessSidechain/DistributedSet.hs
  onchain/src/TrustlessSidechain/FUELMintingPolicy.hs
  onchain/src/TrustlessSidechain/FUELProxyPolicy.hs
  onchain/src/TrustlessSidechain/Governance.hs
  onchain/src/TrustlessSidechain/Governance/Admin.hs
  onchain/src/TrustlessSidechain/Governance/MultiSig.hs
  onchain/src/TrustlessSidechain/IlliquidCirculationSupply.hs
  onchain/src/TrustlessSidechain/InitToken.hs
  onchain/src/TrustlessSidechain/MerkleRootTokenMintingPolicy.hs
  onchain/src/TrustlessSidechain/MerkleRootTokenValidator.hs
  onchain/src/TrustlessSidechain/MerkleTree.hs
  onchain/src/TrustlessSidechain/OffChain.hs
  onchain/src/TrustlessSidechain/PermissionedCandidates.hs
  onchain/src/TrustlessSidechain/Reserve.hs
  onchain/src/TrustlessSidechain/ScriptCache.hs
  onchain/src/TrustlessSidechain/Types.hs
  onchain/src/TrustlessSidechain/Types/Unsafe.hs
  onchain/src/TrustlessSidechain/UpdateCommitteeHash.hs
  onchain/src/TrustlessSidechain/Utils.hs
  onchain/src/TrustlessSidechain/Versioning.hs
  onchain/test/Test/TrustlessSidechain/Golden/Types.hs
  onchain/test/Test/TrustlessSidechain/MerkleProofSerialisation.hs
  onchain/test/Test/TrustlessSidechain/MultiSig.hs
  onchain/test/quickcheck-extra/src/Test/QuickCheck/Extra.hs
  onchain/test/roundtrip/Main.hs
  onchain/test/script-size/Data/Generated.hs
  onchain/test/script-size/Data/Handwritten.hs
  onchain/test/script-size/Main.hs
  onchain/test/script-size/Sizer.hs
  onchain/trustless-sidechain.cabal
Labels: dependencies

#67 use mainnet config, when mainnet is chosen in the config.json
  CHANGELOG.md
  offchain/config.example.json
  offchain/src/TrustlessSidechain/Options/Parsers.purs
  offchain/src/TrustlessSidechain/Options/Specs.purs
  offchain/test/Test/ConfigFile.purs
Labels: bug

#78 Updating the off-chain documentation
  offchain/README.md
Labels: documentation

#72 Clean up off chain code for the native token management
  offchain/src/Main.purs
  offchain/src/TrustlessSidechain/Effects/Env.purs
  offchain/src/TrustlessSidechain/Effects/Errors/Parser.purs
  offchain/src/TrustlessSidechain/InitSidechain/Checkpoint.purs
  offchain/src/TrustlessSidechain/InitSidechain/FUEL.purs
  offchain/src/TrustlessSidechain/InitSidechain/TokensMint.purs
  offchain/src/TrustlessSidechain/NativeTokenManagement/IlliquidCirculationSupply.purs
  offchain/src/TrustlessSidechain/NativeTokenManagement/Reserve.purs
  offchain/src/TrustlessSidechain/NativeTokenManagement/Types.purs
  offchain/src/TrustlessSidechain/Options/Specs.purs
  offchain/src/TrustlessSidechain/Utils/Asset.purs
  offchain/src/TrustlessSidechain/Utils/Utxos.purs
  offchain/src/TrustlessSidechain/Versioning/V1.purs
  offchain/test/Test/IlliquidCirculationSupply.purs
  offchain/test/Test/Reserve.purs
Labels: refactoring
